// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package authapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин.
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// RequestCodeRequest Запрос на отправку OTP-кода на номер телефона.
type RequestCodeRequest struct {
	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// RequestCodeResponse Ответ на запрос OTP-кода.
type RequestCodeResponse struct {
	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах.
	TtlSeconds int `json:"ttl_seconds"`
}

// VerifyCodeRequest Подтверждение OTP-кода и вход/регистрация. Только phone и code: на этом шаге ещё не известно, новый клиент или существующий, поэтому имя здесь не передаётся — для нового клиента оно дозаполняется отдельным шагом (PATCH /profile, шаг 3 SCR-001).
type VerifyCodeRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// VerifyCodeResponse Ответ на подтверждение кода — сессия и данные клиента. Для нового клиента (is_new=true) поле client.name пустое/отсутствует: имя дозаполняется через PATCH /profile (шаг 3 SCR-001). Существующий клиент возвращается с заполненным именем.
type VerifyCodeResponse struct {
	// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
	Client Client `json:"client"`

	// IsNew true, если клиент только что зарегистрирован (имя ещё не задано).
	IsNew bool `json:"is_new"`

	// Token Bearer-токен сессии.
	Token string `json:"token"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// RequestAuthCodeJSONRequestBody defines body for RequestAuthCode for application/json ContentType.
type RequestAuthCodeJSONRequestBody = RequestCodeRequest

// VerifyAuthCodeJSONRequestBody defines body for VerifyAuthCode for application/json ContentType.
type VerifyAuthCodeJSONRequestBody = VerifyCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Выход
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Запросить код подтверждения (OTP)
	// (POST /auth/request-code)
	RequestAuthCode(w http.ResponseWriter, r *http.Request)
	// Подтвердить код и войти/зарегистрироваться
	// (POST /auth/verify-code)
	VerifyAuthCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Выход
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код подтверждения (OTP)
// (POST /auth/request-code)
func (_ Unimplemented) RequestAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить код и войти/зарегистрироваться
// (POST /auth/verify-code)
func (_ Unimplemented) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestAuthCode operation middleware
func (siw *ServerInterfaceWrapper) RequestAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyAuthCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/request-code", wrapper.RequestAuthCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verify-code", wrapper.VerifyAuthCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xaXW/b5vX/Kg/474WM0pIc+58iKnaRBhnWoVmM2tsuEs+gJdpmK5MaSWX1AgF6SZoY",
	"SeN1K9CiWDuku8jFbmjFjGXrxUA+wXm+Qj/JcM55SJESZWVeOmC7CSyJz8t5+53f7zD3tbKzV3Ns0/Y9",
	"rXRfc02v5tieSR8+MCofm7+vm56Pn8qO7Zs2/WnUalWrbPiWYxc+8RwbvzM/M/ZqVZOfrJhaSdsyKpuu",
	"Wq9re6bnGTv4PXwHIXQhlE0YyicQCjiHQDYhgAGEsi2b8omAEwjgXDZhJFsQ5AX8Df/mVfKpbOOqMxjJ",
	"pmxCCGeyDUN8VLblU9wupK+PIYAhniEf4oZDCOQjCGEIPTjNaw1d88q75p6BV37HNbe1kvZ/hbE7Cvyr",
	"V7jpuo6rNRoNXauYXtm1amj4pQwRObwFfe7RQ01deKbhe5tlp277ArowxH2OoYePQQAnMMIlYimfXxbQ",
	"gz70hGvavlGNlhzBCPryqXwMYXKvBbLwQ9s3Xduosg2XiaKldtg0aYtUIF/INowW8R80fSQfQx//RBNk",
	"GwI4w8DBiO2HI9mBUw5dKA/kl4JcdUJL4QReQfhWgvJnGMoOep9CPZSH8lDQ3XpwBGcQCNmikHWhR7mF",
	"Z647zi3D3lfZ7l3KUb7jbO4Z9n6U817aV88xdPIxZi0MBAwwYeEluiuZISPoKp910a2YJ+yxc3LjE9mG",
	"M9l52y5L300+goBKiVI6cTv5RPzY/ErQxxC68gnmHAwFroYB3hQd3abfA+jCGfTE2q21Rdr3GG0SOdxP",
	"HpBVAT09LtcjsjcQ0OMf8INsyYfxYiqEtVtrC9MuwrIfwAheoVtVBuIlhqowXNMz7cqmse2b7qZnlh27",
	"4omcbMEgz3fGMm5PVqu6eMC19GvbqPu7jmv90axcKkPqyQ1SyfEDO0B2CDdamLHB2Dzy2efQk4dk+Bjc",
	"VDUdQwinGDHK6TaEiAcESadYhyM44zB12b6XCBgEpmcQiuvqSnT5t5JN35MJHfq3DV02KsIuDI3CTLxT",
	"8noZFkMvrzXiK1Fd3qhayukTx35LaRjCEFMnXeIC/oT34R+hJx9Aj/zZTDr8nBNnxLgsO4I9CaF8oDA4",
	"R257CT12Jn4vmzCAgMJwM790dQVT8znjmipT2cI9BNn7Eu9D0KSsE7l7pmtt7y9ihujC8jZt8w8/8926",
	"uSBsY8+MkJK7AgaPelpUhh3y8AjCAuZw2unymTyAEJf1YEAQGLfAgAOCkTihQkV7H8svCS478lnmZeUz",
	"kaM6pBKhFBrKw9h92Flp2YlYvb5+4xeiUHOdbatqLuQ1Xau5Ts10fYt5Rdk1Dd+sbBpZYfyK3Mko0KUd",
	"8fYz3Adn46AjlOvatuPu4b5axfDNRd/aMzVd8/drWGae71r2Dqa4Vck4+RsqpDhDsFdwPl50TL1uVbJO",
	"wOhlnkGxSO8nZpQM5yB1d0QiIR9xqz0hlpH0R0+xI+I7UV9JHYIoMRLyMdV/IJZFLiNMMWThRWk3hCnj",
	"s49Me8ff1UpLxaKu7Vl2/DnD8NquY2dZ/l1UWdN1NaOW8gK+kS3ONfkUC2pcrGfILsS4HtO3f/e9a9eu",
	"LV1ZXvn/q+9h9hk+chitpP3u7t137ywtXtu4e7dyf0lfWmm8Mx28hq5hC7dchPk7GsWXrdKTqbsRL3S2",
	"PjHLPhof06zJBkt0aIjVK5tMVpkjhcyYxvSkl1Eu1D2m9vwrBLRqqJCem1VqL11M0s2S8KqOv7ldr1Z1",
	"UXHqW1Vzc8txPrXsHZ1/Kht22axWzYr67PmG6+Mno+qaRmU/+YBl3zOqVmUTb5iOQHxKVm1UTN+wql5m",
	"koREFA8px5OdLBSUHGzwSD5iBkHo8ET1QPqCeswx9DFJjunhgKgJwlMLfSIfCuJZeMxBpAaYWqQqJhS5",
	"baduV6gveuL1i6sLJTHN3jEPZVt28Gi8KgR8MouRDpwnhQnf6+ZS4eYVXVUzHKFIOKcuGLDV8ql4/Q94",
	"Dl38lQjIEEYl8StBZ7Zk+3VfFDIfuaVOxt1e91EaIB5zO4rpFbn1jIAmEIqDTCedcc+wqgamh1IbW47h",
	"VrJi9pwSL8IoxfUZO5X0iu/EMB55aoSBSFlAHYZCN4RQPkQIQsKLIb1o2zR2jUEJpcuO6WLKjc0hiTTf",
	"DOXquTfmxBkwuBH3SBZgbFBcD6IwxZ+R2MUHpm25Mm1LIwN2YiY5ZdULRhjs8aSXE3XDEDRZCiEShaOk",
	"EeFEZ0hlHUciclZKi1IM2/m5+ErwNrYhC1aVLrvhVMzEQGLC1K/H1F1FJaVFZEfcXl+NtEigHhnO7ErT",
	"JfEWO9tP1634knOdyFOeDGO+H2shMiAhiFL+m3ZPlsTKzkjFEwmPE+ymRbjUwTaZEnNJTdaLJjxj9ceU",
	"dTLYKRdfLWZhgu9XL7jncwYcAa9IjgyZbarc6aZuC4F8mDpvuVjMLNxkoJKn69nOy4rib0gvXFwJqI2P",
	"VRyb8IppLdV2ugKIYZO8LmQyfpSbPyQiRLmFy7BkuRkK+QV1sUFELcO0ZEHXdRkdMJg6V1w3Iixjxabk",
	"IbHgA7UgUjE9ONVZS6nDUFopVXNCnb+FSTHkOUksj+WXii2SWooby4jwK4shjzjfZoscSrLjBCuJzUYP",
	"TDBqXf0mlsXajY8Xi8WlhTflduMwkQfF2q01kVv5sfmXq4IC80A2J/g6wsckdlTur+hXsyBD/2+CMp19",
	"NK8W3hjQzmcWR1wYmC80QWgR4hwK5pRqmMxPpvXbV3OTK5fS9iq3QlGmaUaetf7Fgh5tKMV5fwklLnLT",
	"CSngeXbBTVRnl47rEjQc8ACBD2uJ5DXUyBULgykyfTXIyPt4inPRjEnNelCwk/emw4vu1AVx+/7EPOAS",
	"2lnkIvdmjl1gtJCgM1uOUzUNmzqJ86lpT1/uA9NwTXcxMeMaZxULvYsLgLfVI2fFXpiuhYaueWa57lr+",
	"/hr6jp28Redfr6NUjz79PBpc/PK369rU6O6HzJvqghA7CamJydbq7bV1UTDq/m4hMcxKTyrH6+bPIEuC",
	"/Sbu1ovF5TI5gf4klUKpQe6nh8Y+3PX9Go8jLXvbyQCCqREgqYnPucAnOsH8WSAm/kwowfRXAkGJL+55",
	"AxGPwgcid3t9FQvwhZq2P03dQpEjRJLrqx9ODDSjmsMPPdWHW/QNizwWvi8XlWp6KTvQj2YLvuVHPD5j",
	"wRn0ZQeO6EyEQUoeXbtnuh67cSlfzBcx552aaRs1Sytpy/lifpnRfpfyjpOh6uw4dSrxmjOTsKvZoxpJ",
	"KmnakQc8hhxj8DMqzSGVKfroOA7duLpoTk8XcymRPqxoJe0jvoWefrN5pbiSKQETkJ+YjPLmaPRKcWkW",
	"ZsX7F1LvCWjcsW3Uq/78hemXdVTU9b09w92n11ootTB5MIbGjocAQdHZwAfZ5erN02LEKmY4/vsEVe5z",
	"58jO1/FQaY5Y4oohmqJ6zNKMkW0hopwQ6Mk29C2dQ0yN01mx+xFj8JH8QgWZFqaJGIzgNGKO8bQFNQG9",
	"BnrIL4JIOrTk4XSKKCKNzrzBWlT58QOnsv8GL3re7H1JhoZtpAEfe1ljKlGLP80NFF/Ken/DoUAuQmz6",
	"MbPipL7qYyS4Horz0zrx3whwyZVr85dMvo/9N6tItUatdGcjVVNfTytLle8zoF0eMmxfUIOJHnhBCSb/",
	"O4MqwIjvZ5ItMYNE6GoyRv2sP9FDWOPJB9CnkmT2kBfRS4gZ8m2mjMrN0m73vJm6bbYaDGG4cAnmnEWY",
	"GTbeKjF+/wKLUhyzNX7ZFwFbj6deaZBhrfITY8z0cOA/DDEZiiwLYf4+hhbOJuW695NvQBOs/mLSPiMt",
	"/wfwKT3IOZ7AKIUUp8hnCxf5iNphSx5moFb69LRkuLPRwOuYLrI/+jUdxlXXqdTL+GH830KoscMZc6ZF",
	"hCx6yf4qYsaartXdqqLrXqlQMGpW3qvXytX6Vl7NEQr3lrSGPnnamm/sWPYOi/O2qksGDZpZzzvI4/WL",
	"sw7ciJ3zrykHJD5pOkTTKXF7fVWLXgOzuxsbjX8GAAD//3EXU55vJwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
