// Package profileapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package profileapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ChangePhoneConfirmRequest Подтверждение смены номера телефона.
type ChangePhoneConfirmRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// ChangePhoneRequestCodeRequest Запрос на отправку OTP-кода для смены номера телефона.
type ChangePhoneRequestCodeRequest struct {
	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин.
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// RequestCodeResponse Ответ на запрос OTP-кода.
type RequestCodeResponse struct {
	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах.
	TtlSeconds int `json:"ttl_seconds"`
}

// UpdateProfileRequest Запрос на обновление профиля.
type UpdateProfileRequest struct {
	// Name Имя клиента.
	Name string `json:"name"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// Conflict Стандартное тело ошибки.
type Conflict = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// ConfirmPhoneChangeJSONRequestBody defines body for ConfirmPhoneChange for application/json ContentType.
type ConfirmPhoneChangeJSONRequestBody = ChangePhoneConfirmRequest

// RequestPhoneChangeCodeJSONRequestBody defines body for RequestPhoneChangeCode for application/json ContentType.
type RequestPhoneChangeCodeJSONRequestBody = ChangePhoneRequestCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удалить аккаунт
	// (DELETE /profile)
	DeleteAccount(w http.ResponseWriter, r *http.Request)
	// Получить профиль
	// (GET /profile)
	GetProfile(w http.ResponseWriter, r *http.Request)
	// Обновить имя
	// (PATCH /profile)
	UpdateProfile(w http.ResponseWriter, r *http.Request)
	// Подтвердить смену телефона
	// (POST /profile/phone/confirm)
	ConfirmPhoneChange(w http.ResponseWriter, r *http.Request)
	// Запросить код для смены телефона
	// (POST /profile/phone/request-code)
	RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Удалить аккаунт
// (DELETE /profile)
func (_ Unimplemented) DeleteAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить профиль
// (GET /profile)
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить имя
// (PATCH /profile)
func (_ Unimplemented) UpdateProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить смену телефона
// (POST /profile/phone/confirm)
func (_ Unimplemented) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код для смены телефона
// (POST /profile/phone/request-code)
func (_ Unimplemented) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPhoneChange operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPhoneChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPhoneChangeCode operation middleware
func (siw *ServerInterfaceWrapper) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPhoneChangeCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/profile", wrapper.DeleteAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profile", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/profile", wrapper.UpdateProfile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/confirm", wrapper.ConfirmPhoneChange)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/request-code", wrapper.RequestPhoneChangeCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W4bxxV+lcE2FxSy4o+kOjWDXjiq06aoEyFy0AtHFVbkSNqE3GV3l07UgAApxrUM",
	"qVHSGkgQNAmcXviiNxQtWjRFUoCf4Mwr5EmKc2Z2d5ZcSrKrNC3QG5tL7sycn+9852f0iVFyqzXX4U7g",
	"G8VPDI/7NdfxOT28YZXf5X+scz/Ap5LrBNyhj1atVrFLVmC7Tu4D33XwO/6xVa1VuHyzzI2isWGV1z21",
	"3jSq3PetLfwevoEedKEnmjAS+9BjcAYd0YQODKEndkVT7DM4gQ6ciSaMRQs6WQbf4We5ShyIXVw1gLFo",
	"iib0YCB2YYSvil1xgNv16Otj6MAIzxD3cMMRdMR96MEI+vAsazRMwy9t86qFIr/i8U2jaPwsF5sjJ3/1",
	"czc9z/WMRqNhGmXulzy7hoq/lCIsg1LQc59eaprM51bgr5fcuhMw6MII9zmGPr4GHTiBMS5hhWx2kUEf",
	"TqHPPO4EViVccgRjOBUHYg96+l5zpOGy62xW7NLLOdCvuMH6Zr1SMVDzwLIrBAvrrmVXrI0KX1eCbLiW",
	"V/aNYsHUfiNRjGK+MeH6DoOu2IcjstMI3QZDJlpwCmPpVjIA+RI69G1LHOALXRiTrsehR9F+LbF7RZ7s",
	"iKZooxEJHz209Qi65E/0xQjFYT80H5KAYvc8iUI/Sb/DADqIT/nKMQFhDAOWCfEMR6INAzrvyZyJr+DG",
	"zwivh4wsNYYRAjvcFleKXYR/+BLabkiyd8gebzkB9xyrIjV+Gefbaod1TlskvPgYD5/Hf0gYsYd+kp4j",
	"rw0wYGGs9Ef1nknf9sQD8QUj159IPU7gKfSuxIV/hZFoY9SRGUbiUNplD/pwhD5Aj6G1u9AnTsEzb7vu",
	"LcvZUSznv5ShAtddr1rOTsh1ftJWj9BnYg/ZCoYIEUT8EzSXzgxj6CqbhY7tS4udkRn3xS4MRPuqTZaU",
	"TdyHDlEoUZkmndiXwD8j23bFvgwThqthiJJKAJ6RY7uIZbZ6a3We9j1GnVgG9xMPSKsOvR3T9BHp22EI",
	"bfwBH0RL3IsWEwGu3lqdmzYRRsUQxvAUzaoQSMSiCNHjPnfK69ZmwL11n5dcp+yzjGjBMCtl7lIwT7C0",
	"ErwjOfQ9x6oH265n/4mXXwohdX2DBDi+lwYQbcoXLURsJ1aPbPZn6ItDUjxOaiqajqEHz4gouxIumAco",
	"FT3DOETmITd1pX5PMFEQ6Qygx24okUj4K0HTt6RCm/7dha5UKiKtUZQrUSZdvBSNoZ81GpFIFJfL25az",
	"xVe2XYdjUrO9qlabTEiCIDlWzm3CUzKUZHX0PD5gZqbUQ290mLQe9MSnMt9mDdOoeW6Ne4HN/diXk0e9",
	"c3tFwRwVPUGUsszSD82/XWPkuU9Fcw73ikBhFBYWl3BzK0B+NYrGH95/v/zJknmt8YphGsFOjTJv4NnO",
	"FjrF4R+t11DpFDW/oVhAb8e6TGmC7sfPoglDSkQ9djNbuLaUlOrV165fv46i/fzaa5PSvXqnMH99DaUs",
	"mIWlNDEbpoHkZ3sYIHc0mU1ptrVohbvxAS8FVJnE/lSOXHbLfLZPv4wjVBJCknJEm8W+wF+P4VQc/hv+",
	"/t82fKrFK7airQl1viYiRyvtTiZJBp9jRMsfEc/QJ1w3dco6k9SrDCHa06bIEPE8wRpnllmQ3B/JykAl",
	"OioKic97uJRSUzPkB5a5yz17c2ceAWYy2193+Ee/DLw6n2OOVeVhrSHLSaQ/6gbCRNYmjhpDL4cwStKW",
	"+Ew8gJ4sAYdURETNQ0dSGnLZCeEO9d0TX1DB0RafpQorPmMZymSUZIiER+IwMh/2JLTshK3cuL38G5ar",
	"ee6mXeFzKSTkcSvg5XUrzY0PyZwyj3ZpR5R+hvlgEDtdwn/T9aq4r1G2Aj4f2FWexkd2OeXkryTDhghR",
	"Fe9YNM87pl63y6mMZ1V56hnki+R+bEbSkRikvggZgYn7slg9oXpet0df9ZVhL0KVWeIQqtmZ2KMM2mGL",
	"LJPipjig4Su5GyZ66+PfcWcr2DaKhXzeNKq2Ez2nKH4e27wgxTD4SrQk1sQBBlQcrAOsz1kcjz8iHZF/",
	"o0QQQzeNnKJGZbJEpYZihNErmrLNl11GT/YccYHfv2zOhr9Dh1aNVK0UJnBtL5NNNupFFrXDJiu7dexx",
	"N1z3Q9vZMuVPJcsp8UqFl9WzH1hegE9WxeNWeUd/wXbuWhW7vI4SJj2gN91TENG68JRRBLZah4RxvRbs",
	"MQKHVHgs7ssanNhhX1WRqtXuh1mT5g8jmmP0iZ5aaBNxj1Gngsc8COcoKhfrEdNjmU237pSpsvTZ88fX",
	"5opseu6BOBS7oo1Ho6iykT1WY5w2nOkjHSnXzULu5oKpohmOMKmfyQZbai0O2PN/wiO9MYdxkb0ddebP",
	"T1ku9ZVbWmf+/JTBEfGxTEdRg0JmHcjJBFNV/DToZo5HprFNwAs56vxpAdFWaKnxxPQBxpRhyHUj6Il7",
	"NLjYpUbs3G2T3BWTEjb/W9xDyE1NdC5SIxyCXCSxBM5QkhvVHnoARgpF8cByUx0otkbRgUldFqZ1aaTQ",
	"TtSLTWn1WDIM5niaNGpxIyloMhR6WCgc6Ur0JjLDo3MmRvoUT06YshfyK9FbrEMarSZKaznaTdH127gR",
	"Jqdo3XCiqp4Ge1p/nW5MVeIQlWiJuUUh1UaGT3TyekPeD8e62tiLqq3JFiBh72v5NDgHQeUcOR/JWGHw",
	"lHrRkSyUVEfRTUgLHXEvcd5iPp+KOd1j+ulmuvHSvPheDWuyFVlvvFCLBEeUMbtYNYQola9gnXYqDlMa",
	"nxeov66k8plsYvD8aSs0TMPnpbpnBzurpW1elcJucMvj3o067hw+vRlWmL/9/W1jakrxfTR4oFanhfii",
	"fI8NHXr1C62tUS3Iyjurt1nOqgfbOa3rSA5l4nUXj1uK7A2SlL1fz+cXS4H7IXfoI6UTGnrQBQq9FNPA",
	"dhDU5OTFdjbdtLmH5tmDCV8VWRRPQ+p5mmbUHVPToD72E19PV5xnskAewzG2aWrmYTLRpgZLg1kHBpR1",
	"2lGt/ljNF5OiKUbAwvvGylsTDagiAnroS1Dj13CmkrIsVJ7Mqyz3RLThNKwFAzsIeTdlwQBORRuO6Exs",
	"ClV0GaZxl3u+NGghm8/mMQDdGnesmm0UjcVsPrsoK+NtQmDYBkh3VHiQFjz/uMA4TI71sZtsSUOH5ZtM",
	"19o9VrI3yVAKQgI8IjIc4F7fwUMYmeztN9+dLxRy9N/C62x1+d35fP41rMeyiya7sTyfz/8Cu+7P6f6s",
	"D92wXEyYXB7dpklxk5pjgrmphQ+CXmuHZZeML2UZPNRnlCq3hTLTqUMYvy65PX1iF2UCWcJ2493TS0+x",
	"p1IEmkLpTKUBchxF31tlo2j8ilx1o0R3ZZKL44vPhfxSihM/133GZLWsHIP1gBYAYv8881BkIaqW8oVZ",
	"09ZInFxi+kwtwKZVrwQXL0xeARF/1qtVy9vRAalSawKOGDrWlo9cHAbFWsM0tviMoUNsAlkft6kkSmmk",
	"M8meXBaEfQXUhRQn/ZoHcVhOeCh/iVH85Sbaai6WNtI+j1B/Yg9+R6Zsy7qUyiNd1hk+rFlBaTu1hJ/O",
	"A2ETNCs2ZTUg72iG5FstU6i5m6zs41kXnFC72RIHKd5OVDmGLAq4H7zhlneuzNeplVQjWYIEXp03fhq8",
	"fRvXa2qoSPOJswthmL8YTdpfc/y0yI2VVMilMWsqYhtmlF9zNEjKleTdD4pQcy95+RNNbVOm9hqE6f5R",
	"cwDBltGxKXVvErvqSkpeT9HNxo8E4NnXYP9H8SVRvJS/fvGi6A9nrpSwY1weK/BHF1TTtyaXjAiFsvlw",
	"2DkjLL5P0DNdg0QzYFM2O3+h/DxEUbTG4Cw9nsJpchw96vpTrkoNtszsekw5VQugZTnd+JGDKOXu8T8c",
	"SGkjmrSo+pqG1KJNg/2e2JNzEn0Ccirv02fa/786yJYWLrFg8u91riw4v5weN6lLgal75MuFqTauMIp3",
	"koOKO2uNNfzZw06Tfk26esVzy/USPsR/d0MzKBjI9mEexjCgO9inYZ9kmEbdq6ghgV/M5ayanfXrtVKl",
	"vpFVM5rc3YLRMCdPWw2sLdvZoqNQN3Uz2qUp5yUO8uX6+VkHrkX2eaF5hRHeBEZWbaw1/hUAAP//2N57",
	"wa8qAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
